// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary model header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VVORTEX_AFU_SHIM_H_
#define VERILATED_VVORTEX_AFU_SHIM_H_  // guard

#include "verilated.h"
#include "svdpi.h"

class Vvortex_afu_shim__Syms;
class Vvortex_afu_shim___024root;
class Vvortex_afu_shim_VX_commit_if;
class Vvortex_afu_shim_VX_decode_if;
class Vvortex_afu_shim_VX_execute_if__N4;
class Vvortex_afu_shim_VX_fetch_if;
class Vvortex_afu_shim_VX_gpu_pkg;
class Vvortex_afu_shim_VX_ibuffer_if;
class Vvortex_afu_shim_VX_lsu_mem_if__D10_T3;
class Vvortex_afu_shim_VX_lsu_mem_if__N4_D4_T2;
class Vvortex_afu_shim_VX_mem_bus_if__D10_T3;
class Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2a;
class Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2b;
class Vvortex_afu_shim_VX_mem_bus_if__D40_T5;
class Vvortex_afu_shim_VX_mem_bus_if__D40_T7;
class Vvortex_afu_shim_VX_mem_bus_if__D40_T8;
class Vvortex_afu_shim_VX_mem_bus_if__D40_T9;
class Vvortex_afu_shim_VX_mem_bus_if__D4_T2;
class Vvortex_afu_shim_VX_mem_bus_if__D4_T3;
class Vvortex_afu_shim_VX_operands_if;
class Vvortex_afu_shim_VX_schedule_if;
class Vvortex_afu_shim_VX_scoreboard_if;
class Vvortex_afu_shim_VX_warp_ctl_if;
class Vvortex_afu_shim_VX_writeback_if;
class Vvortex_afu_shim___024unit;


// This class is the main interface to the Verilated model
class alignas(VL_CACHE_LINE_BYTES) Vvortex_afu_shim VL_NOT_FINAL : public VerilatedModel {
  private:
    // Symbol table holding complete model state (owned by this class)
    Vvortex_afu_shim__Syms* const vlSymsp;

  public:

    // CONSTEXPR CAPABILITIES
    // Verilated with --trace?
    static constexpr bool traceCapable = false;

    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(&clk,0,0);
    VL_IN8(&reset,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_TxAlmFull,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_TxAlmFull,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_vc_used,1,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_rsvd1,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_hit_miss,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_rsvd0,1,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_cl_num,1,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_resp_type,3,0);
    VL_IN8(&vcp2af_sRxPort_c0_rspValid,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_mmioRdValid,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_mmioWrValid,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_ReqMmioHdr_length,1,0);
    VL_IN8(&vcp2af_sRxPort_c0_ReqMmioHdr_rsvd,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_vc_used,1,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_rsvd1,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_hit_miss,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_format,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_rsvd0,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_cl_num,1,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_resp_type,3,0);
    VL_IN8(&vcp2af_sRxPort_c1_rspValid,0,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_vc_sel,1,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_rsvd1,1,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_cl_len,1,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_req_type,3,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_rsvd0,5,0);
    VL_OUT8(&af2cp_sTxPort_c0_valid,0,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_rsvd2,5,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_vc_sel,1,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_sop,0,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_rsvd1,0,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_cl_len,1,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_req_type,3,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_rsvd0,5,0);
    VL_OUT8(&af2cp_sTxPort_c1_valid,0,0);
    VL_OUT8(&af2cp_sTxPort_c2_mmioRdValid,0,0);
    VL_IN16(&vcp2af_sRxPort_c0_hdr_mdata,15,0);
    VL_IN16(&vcp2af_sRxPort_c0_ReqMmioHdr_address,15,0);
    VL_IN16(&vcp2af_sRxPort_c0_ReqMmioHdr_tid,8,0);
    VL_IN16(&vcp2af_sRxPort_c1_hdr_mdata,15,0);
    VL_OUT16(&af2cp_sTxPort_c0_hdr_mdata,15,0);
    VL_OUT16(&af2cp_sTxPort_c1_hdr_mdata,15,0);
    VL_OUT16(&af2cp_sTxPort_c2_hdr_tid,8,0);
    VL_INW(&vcp2af_sRxPort_c0_data,511,0,16);
    VL_OUTW(&af2cp_sTxPort_c1_data,511,0,16);
    VL_OUT64(&af2cp_sTxPort_c0_hdr_address,41,0);
    VL_OUT64(&af2cp_sTxPort_c1_hdr_address,41,0);
    VL_OUT64(&af2cp_sTxPort_c2_data,63,0);
    VL_OUTW((&avs_writedata)[2],511,0,16);
    VL_INW((&avs_readdata)[2],511,0,16);
    VL_OUT((&avs_address)[2],24,0);
    VL_IN8((&avs_waitrequest)[2],0,0);
    VL_OUT8((&avs_write)[2],0,0);
    VL_OUT8((&avs_read)[2],0,0);
    VL_OUT64((&avs_byteenable)[2],63,0);
    VL_OUT8((&avs_burstcount)[2],3,0);
    VL_IN8((&avs_readdatavalid)[2],0,0);

    // CELLS
    // Public to allow access to /* verilator public */ items.
    // Otherwise the application code can consider these internals.
    Vvortex_afu_shim___024unit* const __PVT____024unit;
    Vvortex_afu_shim_VX_gpu_pkg* const __PVT__VX_gpu_pkg;
    Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2a* const __PVT__vortex_afu_shim__DOT__afu__DOT__cci_vx_mem_bus_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2a* const __PVT__vortex_afu_shim__DOT__afu__DOT__cci_vx_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T9* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__per_cluster_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T9* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__mem_bus_if;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T9* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__l3cache__DOT__core_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__l3cache__DOT__mem_bus_cache_if;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T9* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__l3cache__DOT__mem_bus_tmp_if;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T9* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__per_socket_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T9* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__l2cache__DOT__core_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__l2cache__DOT__mem_bus_cache_if;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T9* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__l2cache__DOT__mem_bus_tmp_if;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__per_core_icache_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache_mem_bus_if;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__per_core_dcache_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T8* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache_mem_bus_if;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T8* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__l1_mem_bus_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T8* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__l1_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T9* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__l1_mem_arb_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__cache_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__arb_core_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__mem_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_core_arb__BRA__0__KET____DOT__core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_core_arb__BRA__0__KET____DOT__arb_core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__core_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__mem_bus_cache_if;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__mem_bus_tmp_if;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__mem_bus_tmp_if;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T8* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__cache_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__arb_core_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T8* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__mem_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_core_arb__BRA__0__KET____DOT__core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_core_arb__BRA__0__KET____DOT__arb_core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__core_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T7* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__mem_bus_cache_if;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T8* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__mem_bus_tmp_if;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T7* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__mem_bus_tmp_if;
    Vvortex_afu_shim_VX_schedule_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__schedule_if;
    Vvortex_afu_shim_VX_fetch_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__fetch_if;
    Vvortex_afu_shim_VX_decode_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__decode_if;
    Vvortex_afu_shim_VX_warp_ctl_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__warp_ctl_if;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__commit_if__BRA__3__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__commit_if__BRA__2__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__commit_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__commit_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_writeback_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__writeback_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_lsu_mem_if__N4_D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__lsu_mem_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_decode_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__per_issue_decode_if;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer_if__BRA__3__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer_if__BRA__2__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_scoreboard_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard_if;
    Vvortex_afu_shim_VX_operands_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__operands_if;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__3__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__2__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_issue_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_execute_if__N4* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__per_block_execute_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__per_block_commit_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_execute_if__N4* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_alus__BRA__0__KET____DOT__pe_execute_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_execute_if__N4* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_alus__BRA__0__KET____DOT__pe_execute_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_alus__BRA__0__KET____DOT__pe_commit_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_alus__BRA__0__KET____DOT__pe_commit_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__gather_unit__DOT__g_out_bufs__BRA__0__KET____DOT__commit_tmp_if;
    Vvortex_afu_shim_VX_execute_if__N4* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__per_block_execute_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__per_block_commit_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__gather_unit__DOT__g_out_bufs__BRA__0__KET____DOT__commit_tmp_if;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__g_lsus__BRA__0__KET____DOT__lsu_slice__DOT__commit_rsp_if;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__g_lsus__BRA__0__KET____DOT__lsu_slice__DOT__commit_no_rsp_if;
    Vvortex_afu_shim_VX_execute_if__N4* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__fpu_unit__DOT__per_block_execute_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__fpu_unit__DOT__per_block_commit_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__fpu_unit__DOT__gather_unit__DOT__g_out_bufs__BRA__0__KET____DOT__commit_tmp_if;
    Vvortex_afu_shim_VX_execute_if__N4* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__per_block_execute_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__per_block_commit_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_execute_if__N4* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__pe_execute_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_execute_if__N4* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__pe_execute_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__pe_commit_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__pe_commit_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__gather_unit__DOT__g_out_bufs__BRA__0__KET____DOT__commit_tmp_if;
    Vvortex_afu_shim_VX_commit_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__commit__DOT__commit_arb_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_lsu_mem_if__N4_D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lsu_dcache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_lsu_mem_if__N4_D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lsu_lmem_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_bus_if__BRA__3__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_bus_if__BRA__2__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_bus_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_lsu_mem_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__dcache_coalesced_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__g_lmem_adapters__BRA__0__KET____DOT__lmem_bus_tmp_if__BRA__3__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__g_lmem_adapters__BRA__0__KET____DOT__lmem_bus_tmp_if__BRA__2__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__g_lmem_adapters__BRA__0__KET____DOT__lmem_bus_tmp_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__g_lmem_adapters__BRA__0__KET____DOT__lmem_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__g_dcache_adapters__BRA__0__KET____DOT__dcache_bus_tmp_if__BRA__0__KET__;

    // Root instance pointer to allow access to model internals,
    // including inlined /* verilator public_flat_* */ items.
    Vvortex_afu_shim___024root* const rootp;

    // CONSTRUCTORS
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    explicit Vvortex_afu_shim(VerilatedContext* contextp, const char* name = "TOP");
    explicit Vvortex_afu_shim(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    virtual ~Vvortex_afu_shim();
  private:
    VL_UNCOPYABLE(Vvortex_afu_shim);  ///< Copying not allowed

  public:
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    /// Are there scheduled events to handle?
    bool eventsPending();
    /// Returns time at next time slot. Aborts if !eventsPending()
    uint64_t nextTimeSlot();
    /// Trace signals in the model; called by application code
    void trace(VerilatedTraceBaseC* tfp, int levels, int options = 0) { contextp()->trace(tfp, levels, options); }
    /// Retrieve name of this model instance (as passed to constructor).
    const char* name() const;

    // Abstract methods from VerilatedModel
    const char* hierName() const override final;
    const char* modelName() const override final;
    unsigned threads() const override final;
    /// Prepare for cloning the model at the process level (e.g. fork in Linux)
    /// Release necessary resources. Called before cloning.
    void prepareClone() const;
    /// Re-init after cloning the model at the process level (e.g. fork in Linux)
    /// Re-allocate necessary resources. Called after cloning.
    void atClone() const;
  private:
    // Internal functions - trace registration
    void traceBaseModel(VerilatedTraceBaseC* tfp, int levels, int options);
};

#endif  // guard
